version: "3"

services:
  django:
    build: .
    container_name: django
    image: py-server:local
    volumes:
      - ./center_fsp:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - migration

  postgres:
    image: postgres:14-alpine
    container_name: fsp
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=fsp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -p 5432" ]
      interval: 5s
      timeout: 10s
      retries: 5

  migration:
    build: .
    container_name: django-migration
    command: >
      sh -c "
      python manage.py migrate --noinput &&
      python manage.py loaddata fixtures/data.json
      "
    volumes:
      - ./center_fsp:/usr/src/app
    environment:
      - POSTGRES_DB=fsp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    depends_on:
      - postgres