# Generated by Django 4.2.16 on 2024-12-06 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("meropriations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meropriation",
            name="region",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meropriation_regions",
                to="users.region",
                verbose_name="регион",
            ),
        ),
        migrations.AddField(
            model_name="meropriation",
            name="structure",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meropriation_structures",
                to="meropriations.structure",
                verbose_name="состав",
            ),
        ),
        migrations.AddField(
            model_name="meropriation",
            name="tip",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meropriation_tips",
                to="meropriations.tip",
                verbose_name="тип соревнования",
            ),
        ),
    ]
