# Generated by Django 4.2.16 on 2024-12-06 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("meropriations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Statement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("consideration", "Consideration"),
                            ("acceptance", "Accept"),
                        ],
                        default="consideration",
                        max_length=30,
                        verbose_name="статус заявки",
                    ),
                ),
                (
                    "meropriations",
                    models.ManyToManyField(
                        to="meropriations.meropriation", verbose_name="мероприятия"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "заявка",
                "verbose_name_plural": "заявки",
                "ordering": ("id",),
            },
        ),
    ]
